version: '3'

services:
  app:
    build: src/
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    volumes:
      - ./src/static:/usr/src/app/static
    depends_on:
      - db
#    env_file:
#      - ./.env

  nginx:
    build: ./nginx
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    ports:
      - 80:80
    volumes:
      - ./src/static:/usr/src/app/static
    depends_on:
      - app

  db:
    image: postgres:12.0-alpine
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    volumes:
      - ./data/db:/var/lib/postgresql/data/
#    env_file:
#      - ./.env.db