name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3

#     Set global environment variables:
      - name: Set global env
        id: global_env
        run: |
          echo "::set-output name=DOCKERHUB_IMAGE_NAME::docker.pkg.github.com/thesisdjangosecurity/thesisdjangosecurity"

#     Build Docker image:
      - name: Build and tag app image
        run: |
          docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

#     Publish image to github package repository:
      - name: Publish app image
        run: docker push "docker.pkg.github.com/thesisdjangosecurity/thesisdjangosecurity"