name: Docker CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    env:
      RESTART_APP: no
      APP_SECRET_KEY: test
      APP_DEBUG: False
      APP_ALLOWED_HOSTS: test.com
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker-compose build
      - name: Init test ssl for nginx
        run: |
          ./init_test_ssl_for_nginx.sh
      - name: Run docker-compose services
        run: |
          docker-compose up -d
      - name: Check services status
        run: |
          ./docker_services_cheker.sh
