name: Docker CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    env:
      APP_DOCKER_IMAGE: app
      APP_SECRET_KEY: test
      APP_DEBUG: False
      APP_ALLOWED_HOSTS: test.com
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

    steps:
      - uses: actions/checkout@v3
      - name: Build the app Docker image
        run: |
          docker build -t app src/
      - name: Build the docker-compose
        run: |
          docker-compose build
      - name: Run docker-compose services
        run: |
          docker-compose up -d
