name: Docker Bench Security

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  analyze_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker Bench for Security
        run: |
          git clone https://github.com/docker/docker-bench-security.git
      - name: Perform Docker Analysis
        run: |
          cd docker-bench-security
          sudo sh docker-bench-security.sh